### ISSUE TITLE
Unable to parse non-quoted "algorithm" and "stale" property in Digest www-authenticate header

### ISSUE THREAD

**Issue by jakepruitt** [nfroidure/http-auth-utils#10]
## Issue

I'm a gentledev I:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked I'm up to date with the latest version of the project

### Expected behavior

When receiving a Digest authentication header from a server with the following fields:

```
Digest realm="me@yahoo.com", nonce="fff...", qop="auth", opaque="aaa...", algorithm=MD5, stale=FALSE
```

I would expect the parser to handle the lack of quotes around `MD5` and `FALSE`.

### Actual behavior

When parsing the above example header, the http-auth-utils library throws this error:

```
YError: E_MALFORMED_QUOTEDKEYVALUE (4, algorithm=MD5, stale=FALSE, 3): E_MALFORMED_QUOTEDKEYVALUE
    at map (/Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/src/utils.ts:21:15)
    at Array.map (<anonymous>)
    at parseHTTPHeadersQuotedKeyValueSet (/Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/src/utils.ts:16:6)
    at Object.parseWWWAuthenticateRest (/Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/src/mechanisms/digest.ts:100:12)
    at some (/Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/src/index.ts:101:29)
    at Array.some (<anonymous>)
    at Object.parseWWWAuthenticateHeader (/Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/src/index.ts:94:18)
    at Object.getDigestAuthorizationHeader (/Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/worker/src/lib/digest.ts:46:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/worker/src/synthetics-http/http-request.ts:216:33 {
  code: 'E_MALFORMED_QUOTEDKEYVALUE',
  params: [ 4, 'algorithm=MD5, stale=FALSE', 3 ],
  wrappedErrors: []
}
```

### Steps to reproduce the behavior

```
> const httpAuth = require('http-auth-utils')
> httpAuth.parseWWWAuthenticateHeader('Digest realm="me@yahoo.com", nonce="fff", qop="auth", opaque="aaa", algorithm=MD5, stale=FALSE')
Uncaught YError: E_MALFORMED_QUOTEDKEYVALUE (4, algorithm=MD5, stale=FALSE, 3)
    at /Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/dist/utils.js:24:13
    at Array.map (<anonymous>)
    at parseHTTPHeadersQuotedKeyValueSet (/Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/dist/utils.js:19:49)
    at Object.parseWWWAuthenticateRest (/Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/dist/mechanisms/digest.js:62:57)
    at /Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/dist/index.js:105:29
    at Array.some (<anonymous>)
    at Object.parseWWWAuthenticateHeader (/Users/jake.pruitt/go/src/github.com/DataDog/synthetics-worker/node_modules/http-auth-utils/dist/index.js:101:18) {
  code: 'E_MALFORMED_QUOTEDKEYVALUE',
  params: [ 4, 'algorithm=MD5, stale=FALSE', 3 ],
  wrappedErrors: []
}
```

### Debugging informations
- `node -v` result:
```
v12.22.4
```

- `npm -v` result:
```
6.14.14
```

**Comment by nfroidure** [comment]
Thanks for reporting, feel free to PR otherwise I'll try to have a look when possible.
